version: '3.1'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=your_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: